# Generated by Django 3.0 on 2019-12-26 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='st1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judge', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('valor1', models.FloatField()),
                ('valor2', models.FloatField()),
                ('valor3', models.FloatField()),
                ('valor4', models.FloatField()),
                ('partid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lines.part')),
            ],
        ),
    ]
